version: '3.9'

services:

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - main
    restart: on-failure

  app:
    build: .
    image: app-image
    command: python manage.py runserver 0.0.0.0:8000
    container_name: app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    hostname: app
    networks:
      - main
    restart: on-failure

  celery_worker:
    command: sh -c "celery -A nordigen worker -l info"
    depends_on:
      - app
      - redis
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    hostname: celery_worker
    image: app-image
    networks:
      - main
    restart: on-failure

networks:
  main:

volumes:
  redis_data: