# Generated by Django 4.0.1 on 2022-01-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('access_expires', models.DateTimeField()),
                ('refresh_token', models.TextField()),
                ('refresh_expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=250)),
                ('agreement', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('requisition_id', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=250)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais_api.useragreement')),
            ],
        ),
    ]
